### ISSUE TITLE
metadata upload performance issues following merge of pull request 17

### ISSUE THREAD

**Issue by ngeraci** [ucldc/nuxeo_spreadsheet#18]
Following #17 being merged in Jan. 2018, the performance of the uploader tool has slowed significantly, becoming cumbersome for use with larger collections and sometimes introducing errors. Per @tingletech, it seems to be making ~10 requests per item.

### If you've updated, but want to revert to the previous version:
In the `nuxeo_spreadsheet` directory on your local machine, use the command `git checkout 34f7d148e`. 

## Details
Testing on the same set of 10 items (in Windows 7):

|                      | OLD      | NEW      |
|----------------------|----------|----------|
| Python 2             | 0m5.959s | 1m9.978s |
| Python 2 `--dry-run` | 0m0.440s | 1m2.769s |
| Python 3             | n/a      | 1m4.925s |
| Python 3 `--dry run` | n/a      | 1m0.090s |

In my existing Python 2 environment for this tool on Windows 7, I also ran into the following error repeatedly in working with larger collections using the new version:

```requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nuxeo.cdlib.org', port=443): Max retries exceeded with url: /Nuxeo/site/api/v1/path/asset-library/UCR/Manuscript%20Collections/ms146/curivsc_146_001_246.jpg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000000466C7B8>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))```

I've had the best luck so far running the new version in a new Python 3 environment in Ubuntu 16.04, but it still feels relatively flaky and slow, and not quite stable enough to rely on day-to-day.

**Comment by ngeraci** [comment]
I've been looking into this a little further and it seems like the issue of excessive requests (and slowness) may lie with the  ``set_list_element`` and ``set_dict_element`` functions in CsvtoDict.py. They both call ``get_existing_data``, so make a ``nx.get_metadata`` request for each list or dict element they construct:

https://github.com/ucldc/nuxeo_spreadsheet/blob/d419e9f311fde0ed29f28d07dca75705614dbd74/csv2dict/Csv2Dict.py#L134-L185

I have a couple current projects that would be made easier by being able to upload out-of-order spreadsheets, so I may have some time to get this better figured out. It seems like there should be a better way to build the complex elements than relying on calls to the existing data.

**Comment by tingletech** [comment]
good catch Noah, I think I see a way to speed this up

**Comment by tingletech** [comment]
@ngeraci can you try the changes in #19 and see if that is faster?

**Comment by ngeraci** [comment]
@tingletech -- just tested it out, it's substantially faster. thank you!
